# ---------------------------------------------------------------------------------------------------------------------
# modules/postgres-bootstrap/versions.tf — Component 16 (Database Initialisation).
# Uses the cyrilgdn/postgresql provider (the maintained fork; HashiCorp's old terraform-providers/postgresql is
# archived). Pinned. The aws provider is generated by the root terragrunt.hcl and read here for the master secret.
# ---------------------------------------------------------------------------------------------------------------------
terraform {
  required_version = ">= 1.9"

  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.23"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
}
